spring:
  application:
    name: Consumer

server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: consumer