spring:
  application:
    name: consumer

server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
#    preferIpAddress: true
#    hostname: consumer