spring:
  application:
    name: zuul-service-gw
    
server:
  port: 7000
  servlet:
    context-path: /zuul-gw
  
info:
  app:
    name: ZUUL Service - Instance
    description: My Boot App
    version: 1.0.0
    
zuul:
  routes:
    producer:
      path: /producer/**
      service-id: producer
    consumer:
      path: /consumer/**
      service-id: consumer
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka,http://localhost:8000/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}
    hostname: localhost
    preferIpAddress: true
    status-page-url: http://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/actuator/info
    health-check-url-path: http://${eureka.instance.hostname}:${server.port}/${server.servlet.context-path}/actuator/health
    
ribbon:
  eureka:
    enabled: true