spring:
  application:
    name: eureka-server(peer2)
server:
  port: 8001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: eureka-server(peer2)
    hostname: peer2