spring:
  application:
    name: eureka-server(peer1)
server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    instance-id: ${spring.application.name}
#    hostname: peer1