spring:
  application:
    name: Producer

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    hostname: producer